---
title: "Visualization"
author: "Shelly Kinney, Joshua Kemp, Yue Liu"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Process output files from RNA-seq analysis

## Run these in the terminal
##copy the necessary files and create a file with the list of names
```{r}
git clone https://github.com/0Yue0/BCB546_Spring2023_Final.git
cp ./BCB546_Spring2023_Final/readcounts/* .
ls *readcounts.tab > filenames.txt
```



#start of R scripting
```{r}
library(tidyverse)
library(dplyr)
library(rmarkdown)
library(stats)
library(knitr)
library(readxl)

```


# Run this in R
# merge all readcount data into one dataframe
```{r}
list.files <- scan("filenames.txt", what="", sep="\n")
file_names <- list.files(pattern = "\\.tab") #create an r list with the files names from the txt file
files <- lapply(file_names, function(x) read.table(x, header = FALSE)) # load in files
reduced_files <- lapply(files, function(x) x[,1:2])
merged_files <- suppressWarnings(Reduce(function(x, y) merge(x, y, by = "V1"), reduced_files)) # merge the files by the first column
colnames(merged_files) <- c("Merge_Col", file_names)


```




```{r}
library(pheatmap)
library(tidyverse)
#install.packages("hrbrthemes")
library(hrbrthemes)
library(viridis)
#install.packages("plotly")
library(plotly)
#install.packages("plotl")
#install.packages("d3heatmap")
#install.packages("png")
library("png")
#install.packages("d3heatmap_0.6.1.2.tar.gz", repso=NULL, type="source")
library(d3heatmap)
#install.packages("heatmaply")
library(heatmaply)
library(gtable)
```



# figure S4 (heatmap)- data processing
```{r}

fs4_data <- merged_files[,c(1:17, 27:42)]   # select corresponding cell types
fs4_data <- fs4_data[,c(1,18:33,2:17)]      # reorder the cel tlypes - same with the paper's

# specific gene list
fs4_list <-  c ("AT4G39340","AT5G64720","AT2G21740","AT1G76750","AT2G21750","AT1G74480",
                "AT1G26795","AT1G60985","AT2G02515","AT2G20595","AT2G35670","AT3G04540",
               "AT3G10890","AT3G24510","AT4G25530","AT5G04560","AT5G27880","AT5G38330")

fs4_all <- fs4_data %>% 
  filter(Merge_Col %in% fs4_list) %>%  # filter based gene ID
  slice(match(fs4_list, Merge_Col))    # reorder rows with specified order

rownames(fs4_all) <- fs4_all[,1]       # using first column as row names
  
fs4_all <- fs4_all %>% dplyr::select(-Merge_Col) # delete first column

fs4_all <- as.matrix(fs4_all)         # covert into matrix for heatmap plotting
```



```{r}
# plotting


# annotations to rows
annotation.row = data.frame(
                    GeneClass = factor(rep(c("Egg cell specific genes", "Central cell specific genes"), c(6,12)))
                )

rownames(annotation.row) <- rownames(fs4_all)


# annotations to columns
annotation.col = data.frame(
  CellType = factor(rep(c("ECd", "ECt", "CCd", "CCt"), c(8,8,8,8)))
)

rownames(annotation.col) = colnames(fs4_all)


# plotting
fs4 <- pheatmap(fs4_all,
         cluster_rows = F, 
         cluster_cols = F,
         annotation_row = annotation.row,
         annotation_col = annotation.col,
         gaps_row = c(6),
         gaps_col = rep(c(24,16,8)),
         show_colnames = F,
         cellwidth = 10,
         cellheight = 18,
         scale = "row"
         )

# export figures
pheatmap(fs4_all,
         cluster_rows = F,
         cluster_cols = F,
         annotation_row = annotation.row,
         annotation_col = annotation.col,
         gaps_row = c(6),
         gaps_col = rep(c(24,16,8)),
         show_colnames = F,
         cellwidth = 10,
         cellheight = 18,
          scale = "row",
         filename = "Figure_S4.png"
        )


```



